/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ayan
 */
public class RemoveSection extends javax.swing.JPanel {

    /**
     * Creates new form RemoveSection
     */
    public RemoveSection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barcodeLabel = new javax.swing.JLabel();
        barcodeField = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        barcodeLabel.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        barcodeLabel.setForeground(java.awt.Color.blue);
        barcodeLabel.setText("Enter barcode to Remove:");

        barcodeField.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        barcodeField.setForeground(java.awt.Color.magenta);

        search.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        search.setForeground(java.awt.Color.magenta);
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/serach.png"))); // NOI18N
        search.setText("Search");

        remove.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        remove.setForeground(java.awt.Color.red);
        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/remove.png"))); // NOI18N
        remove.setText("Remove");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(barcodeLabel)
                .addGap(69, 69, 69)
                .addComponent(barcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(search)
                .addGap(27, 27, 27)
                .addComponent(remove)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcodeLabel)
                    .addComponent(barcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search)
                    .addComponent(remove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField barcodeField;
    private javax.swing.JLabel barcodeLabel;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton remove;
    public javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
